### ISSUE TITLE
.cndb format ?

### ISSUE THREAD

**Issue by debugpoint136** [Matheus-Mello/NDB-Converters#1]
Hi, https://ndb.rice.edu/ndb-format page mentions a *.cndb* format.

Is the converter for NDB to CNDB available on this repo yet?

**Comment by mellofariam** [comment]
We'll be adding it tomorrow or the day after.

**Comment by debugpoint136** [comment]
Thanks @Matheus-Mello Looking forward to it.

**Comment by debugpoint136** [comment]
Just checking in...
